"""Render product mockups (t-shirt, hoodie, sweatshirt, mug, tumbler) for
a design already generated by `pipeline.generate` - a quick way to
sanity-check placement/scale/color before setting up Printify or spending
time in its own mockup generator.

Usage:
    python -m pipeline.mockup_preview \\
        --design output/halloween_vintage_apparel_canva/<slug> \\
        --products tshirt hoodie sweatshirt mug \\
        --garment black

    python -m pipeline.mockup_preview \\
        --design output/halloween_pattern_tumblers/<slug> \\
        --products tumbler mug
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image

from design import mockup

# All-over patterns (design/generators/pattern.py) wrap edge to edge;
# box-print designs (apparel_graphic, canva) are centered as a patch -
# detected from each design's metadata.json "generator_type".
COVER_GENERATOR_TYPES = {"pattern"}

MOCKUP_FN = {
    "tshirt": mockup.mockup_tshirt,
    "hoodie": mockup.mockup_hoodie,
    "sweatshirt": mockup.mockup_sweatshirt,
    "mug": mockup.mockup_mug,
    "tumbler": mockup.mockup_tumbler,
    "framed": mockup.mockup_framed_wall,
    "flatlay": mockup.mockup_desk_flatlay,
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Render garment/mug/tumbler mockups for a generated design.")
    parser.add_argument("--design", required=True, help="Path to a design directory (output/<niche>/<slug>) or a direct image file")
    parser.add_argument("--products", nargs="+", default=["tshirt", "hoodie", "sweatshirt", "mug"], choices=list(MOCKUP_FN))
    parser.add_argument("--garment", default=None, help="Garment color key (see design/mockup.py GARMENT_COLORS); default varies per product")
    parser.add_argument("--out", default=None, help="Output directory (default: alongside the design)")
    args = parser.parse_args()

    design_path = Path(args.design)
    cover = False
    if design_path.is_dir():
        metadata = json.loads((design_path / "metadata.json").read_text())
        cover = metadata.get("generator_type") in COVER_GENERATOR_TYPES or metadata.get("pod_fit") == "cover"
        png_files = metadata.get("files", {}).get("png", {})
        apparel_png = next((p for s, p in png_files.items() if "apparel" in s), None)
        mug_png = next((p for s, p in png_files.items() if "mug" in s), None)
        tumbler_png = next((p for s, p in png_files.items() if "tumbler" in s), None)
        framed_png = next((p for s, p in png_files.items() if "poster" in s), None) or next(iter(png_files.values()), None)
        out_dir = Path(args.out) if args.out else design_path
    else:
        apparel_png = mug_png = tumbler_png = framed_png = str(design_path)
        out_dir = Path(args.out) if args.out else design_path.parent

    out_dir.mkdir(parents=True, exist_ok=True)

    source_by_product = {"mug": mug_png, "tumbler": tumbler_png, "framed": framed_png, "flatlay": framed_png}
    for product in args.products:
        source = source_by_product.get(product, apparel_png)
        if not source:
            print(f"skip {product}: no matching size found in this design's files")
            continue
        design_img = Image.open(source)
        kwargs = {"garment": args.garment} if args.garment else {}
        if product == "mug" and cover:
            kwargs["cover"] = True
        result = MOCKUP_FN[product](design_img, **kwargs)
        out_path = out_dir / f"mockup_{product}.png"
        result.save(out_path)
        print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
