"""Render product mockups (t-shirt, hoodie, sweatshirt, mug) for a design
already generated by `pipeline.generate` - a quick way to sanity-check
placement/scale/color before setting up Printify or spending time in its
own mockup generator.

Usage:
    python -m pipeline.mockup_preview \\
        --design output/halloween_apparel_graphics/<slug> \\
        --products tshirt hoodie sweatshirt mug \\
        --garment black
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image

from design import mockup

MOCKUP_FN = {
    "tshirt": mockup.mockup_tshirt,
    "hoodie": mockup.mockup_hoodie,
    "sweatshirt": mockup.mockup_sweatshirt,
    "mug": mockup.mockup_mug,
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Render garment/mug mockups for a generated design.")
    parser.add_argument("--design", required=True, help="Path to a design directory (output/<niche>/<slug>) or a direct image file")
    parser.add_argument("--products", nargs="+", default=["tshirt", "hoodie", "sweatshirt", "mug"], choices=list(MOCKUP_FN))
    parser.add_argument("--garment", default=None, help="Garment color key (see design/mockup.py GARMENT_COLORS); default varies per product")
    parser.add_argument("--out", default=None, help="Output directory (default: alongside the design)")
    args = parser.parse_args()

    design_path = Path(args.design)
    if design_path.is_dir():
        metadata = json.loads((design_path / "metadata.json").read_text())
        png_files = metadata.get("files", {}).get("png", {})
        apparel_png = next((p for s, p in png_files.items() if "apparel" in s), None)
        mug_png = next((p for s, p in png_files.items() if "mug" in s), None)
        out_dir = Path(args.out) if args.out else design_path
    else:
        apparel_png = mug_png = str(design_path)
        out_dir = Path(args.out) if args.out else design_path.parent

    out_dir.mkdir(parents=True, exist_ok=True)

    for product in args.products:
        source = mug_png if product == "mug" else apparel_png
        if not source:
            print(f"skip {product}: no matching size found in this design's files")
            continue
        design_img = Image.open(source)
        kwargs = {"garment": args.garment} if args.garment else {}
        result = MOCKUP_FN[product](design_img, **kwargs)
        out_path = out_dir / f"mockup_{product}.png"
        result.save(out_path)
        print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
